apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: third-person-ue51-las1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: shared-nvme-las1
---
apiVersion: v1
kind: Pod
metadata:
  name: data-copy
  labels:
    app: data-copy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - LAS1
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: third-person-ue51-las1
  containers:
    - name: copy
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
      image: "alpine:latest"
      command: ["sleep", "infinity"]
      volumeMounts:
        - mountPath: "/data"
          name: data
