apiVersion: v1
kind: Pod
metadata:
  labels:
    name: third-person-ue51
  name: third-person-ue51
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: gpu.nvidia.com/class
            operator: In
            values:
            - RTX_A4000
        weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu.nvidia.com/class
            operator: In
            values:
            - RTX_A4000
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - LAS1
  automountServiceAccountToken: false
  containers:
  - command: [ "/bin/sh", "-c" ]
    #args: [ "while true ; do sleep 86400 ; done" ]
    args:
    - cd /home/ue4/project && ./ThirdPersonTemplate.sh
      -AudioMixer
      -Vulkan
      -Unattended
      -RenderOffScreen
      -FullStdOutLogOutput
      -LogCmds=PixelStreamingWebRTC Verbose
      -AllowPixelStreamingCommands
      -ResX=1920 -ResY=1080
      -PixelStreamingURL=ws://localhost:8888
    image: ghcr.io/epicgames/unreal-engine:runtime-pixel-streaming
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - pgrep -if thirdpersontemplate | xargs kill -2
    name: unreal
    resources:
      limits:
        cpu: 16000m
        memory: 16000Mi
        nvidia.com/gpu: "1"
      requests:
        cpu: 16000m
        memory: 16000Mi
        nvidia.com/gpu: "1"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/ue4/project/
      name: tpt-content
      subPath: Linux/
  - image: ghcr.io/epicgames/pixel-streaming-signalling-server:5.1
    imagePullPolicy: IfNotPresent
    name: signallingwebserver
    resources:
      requests:
        cpu: 256m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/SignallingWebServer/config.json
      name: signalling-config
      subPath: config.json
  enableServiceLinks: true
  imagePullSecrets:
  - name: ghcr-epicgames-docker-credentials
  restartPolicy: Always
  schedulerName: prioritize-image-locality
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: signalling-config
    configMap:
      name: third-person-ue51
  - name: tpt-content
    persistentVolumeClaim:
      claimName: third-person-ue51-las1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: public-las1
    metallb.universe.tf/allow-shared-ip: default
  name: third-person-ue51
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: signalling
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: third-person-ue51
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: third-person-ue51
data:
  config.json: |
    {
        "peerConnectionOptions": "{ \"iceServers\": [{\"urls\": [\"stun:stun.l.google.com:19302\"]}] }",
        "UseFrontend": false,
        "UseMatchmaker": false,
        "UseHTTPS": false,
        "UseAuthentication": false,
        "LogToFile": true,
        "LogVerbose": true,
        "HomepageFile": "player.html",
        "AdditionalRoutes": {},
        "EnableWebserver": true,
        "MatchmakerAddress": "",
        "MatchmakerPort": "9999",
        "PublicIp": "localhost",
        "HttpPort": 80,
        "HttpsPort": 443,
        "StreamerPort": 8888,
        "SFUPort": 8889,
        "MaxPlayerCount": -1
    }
immutable: false
